[package]
name = "tsp-jsc"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Small JavaScriptCore ownership boundary for TSP"
build = "build.rs"

[dependencies]
tsp-js = { path = "../tsp-js" }
mimalloc = "0.1"

[features]
default = ["mock"]
mock = []
native-ffi = []

[build-dependencies]
cc = "1"
