// Generated by `tspserver_v2 typings`. Do not edit by hand.
//
// Plan §16.2 ("`tsp:html`") freezes a single-name surface:
// `raw`. The page reaches it as:
//
// ```ts
// import { raw } from "tsp:html";
// const node = raw("<strong>already safe</strong>");
// ```
//
// `raw` is also re-exported from `tsp:server` (same
// `__tspRaw__` builtin), so a page that already imports
// `raw` from one module does not need to re-import it
// from the other. The typings preserve that symmetry.

declare module "tsp:html" {
  /** A `__tspRaw` value the renderer emits verbatim (slice 6
   * + slice 11). Same shape as `tsp:server.RawNode`; the two
   * declarations are intentionally identical. */
  export interface RawNode {
    readonly __tspRaw: string;
  }
  /** Wrap a value as a `RawNode`. The renderer will emit it
   * verbatim. The application is responsible for ensuring the
   * string is already safe HTML. */
  export function raw(value: unknown): RawNode;
}
