// Generated by `tspserver_v2 typings`. Do not edit by hand.
//
// Plan §16.1 ("`tsp:server`") freezes the importable surface for
// the request / response / fragment / id-gen / validation / db /
// bun-builtin helpers. The shape below mirrors the wrap-prelude's
// `__tspServer = Object.freeze({...})` in `bun/src/runtime/tsp/jsx.rs`,
// the `__tspUtilNs__` namespace in the same file, and the
// per-request Context the host hands the page via the env-var
// Context JSON. If a future slice adds a new name to the wrap,
// this file MUST grow the matching declaration in the same
// commit -- the e2e (`tspserver_v2_typings_emits_three_dts_files`)
// pins the exact strings below so a drift between the runtime
// and the typings surfaces as a hard test failure.
//
// How to wire it up: the `tspserver_v2 typings --out .tsp-types`
// subcommand writes this file (plus `tsp-html.d.ts` and
// `tsp-runtime.d.ts`) into the directory the user passes. Add
// the directory to your `tsconfig.json` `include` (or use a
// triple-slash reference) and the `tsp:server` module becomes
// available to every `.tsp` file in your project.
//
// Bun-builtin types (`Bun.password`, `Bun.markdown`, etc.) are
// intentionally NOT re-exported from `bun-types` here. The user
// can install `bun-types` and augment the `UtilNamespace`
// interface themselves if they need the full typing; the slice
// 18 surface we expose is hand-rolled so the user does not need
// a devDependency just to satisfy the type-checker.

declare module "tsp:server" {
  // -------------------------------------------------------------
  // Request / response surface (plan §13 / §10)
  // -------------------------------------------------------------

  /** Standard HTTP methods. The host uppercases the request
   * method before handing it to the page. */
  export type HttpMethod =
    | "GET"
    | "POST"
    | "PUT"
    | "PATCH"
    | "DELETE"
    | "HEAD"
    | "OPTIONS";

  /** Per-request cookie options (plan §15). The host's
   * Set-Cookie serializer handles the same option set;
   * the application can read it back via `ctx.cookies.get(...)`
   * on a later request. */
  export interface CookieOptions {
    path?: string;
    domain?: string;
    maxAge?: number;
    expires?: Date;
    httpOnly?: boolean;
    secure?: boolean;
    sameSite?: "Strict" | "Lax" | "None";
  }

  /** Per-request cookie surface (plan §15). Reads are a
   * case-sensitive map; writes are buffered into the response
   * envelope and merged by the host into a `Set-Cookie` wire
   * line per call (multi-value cookies do not collapse). */
  export interface CookieJar {
    get(name: string): string | undefined;
    has(name: string): boolean;
    set(name: string, value: string, options?: CookieOptions): void;
    delete(name: string, options?: CookieOptions): void;
  }

  /** Per-request session view (plan §16). The host resolves
   * the request's `tsp_sid` cookie against the runtime
   * SessionService and hands the page a fresh `(id, data)`
   * snapshot. The page's writes travel back through the
   * envelope's `session_writes` field and are applied by the
   * host before the response is sent. */
  export interface SessionView {
    id: string;
    data: Readonly<Record<string, unknown>>;
  }

  /** A service descriptor the page reads from `ctx.services`
   * (plan §17). The runtime ships a small set of known kinds
   * (counter, kv, feature_flag, logger, session, time); the
   * host's `load_counter_services_from_config` (slice 22 +
   * Amendment 3) can also surface user-declared kinds. Use
   * a kind-narrowing `if ("hits" in svc)` guard before
   * reading kind-specific fields. */
  export type ServiceDescriptor =
    | { readonly kind: "counter"; readonly hits: number; readonly [k: string]: unknown }
    | { readonly kind: "kv"; readonly entries: Readonly<Record<string, string>>; readonly [k: string]: unknown }
    | { readonly kind: "feature_flag"; readonly flags: Readonly<Record<string, boolean>>; readonly [k: string]: unknown }
    | { readonly kind: "logger"; info: (...args: unknown[]) => void; warn: (...args: unknown[]) => void; error: (...args: unknown[]) => void; debug: (...args: unknown[]) => void; readonly [k: string]: unknown }
    | { readonly kind: "session"; readonly [k: string]: unknown }
    | { readonly kind: "time"; readonly iso: string; readonly unix_ms: number; readonly [k: string]: unknown }
    | { readonly kind: string; readonly [k: string]: unknown };

  /** Per-request Context (plan §13). Owned by the host, valid
   * only for the duration of the handler call. Subsequent
   * access (after the handler returns) raises a runtime
   * error. Async services SHOULD accept `ctx.signal` and
   * propagate cancellation. */
  export interface Context {
    readonly method: HttpMethod;
    readonly path: string;
    readonly url: URL;
    readonly query: URLSearchParams;
    readonly params: Readonly<Record<string, string>>;
    readonly headers: Readonly<Record<string, string>>;
    readonly request: Request;
    readonly signal: AbortSignal;
    readonly cookies: CookieJar;
    readonly session: SessionView | null;
    readonly services: Readonly<Record<string, ServiceDescriptor>>;
    /**
     * Returns the host-assigned URL for a fragment exported by
     * this page (plan §14, FREEZE item 7, Amendment 4). The
     * application MUST go through this builder instead of
     * hard-coding the internal `/__tsp/fragment` path. The
     * second arg is optional extra query params (e.g.
     * `ctx.fragment("echo", { msg: "hi" })`).
     */
    fragment(name: string, params?: Record<string, string>): string;
  }

  // -------------------------------------------------------------
  // Response builders (plan §10)
  // -------------------------------------------------------------

  /** Build a `Response` with `Content-Type: application/json`. */
  export function json(value: unknown, init?: ResponseInit): Response;
  /** Build a `Response` with `Content-Type: text/plain`. */
  export function text(value: unknown, init?: ResponseInit): Response;
  /** Build a `Response` with `Content-Type: text/html`. */
  export function html(value: unknown, init?: ResponseInit): Response;
  /** Build a 30x redirect `Response` with the `Location` header. */
  export function redirect(
    location: string,
    status?: 301 | 302 | 303 | 307 | 308
  ): Response;
  /** Build a 404 `Response` (`text("Not Found", { status: 404 })`). */
  export function notFound(): Response;

  /** Throw an `HttpError` from inside a handler. The host's
   * wrap catches it and turns it into a `Response` with the
   * matching status. Use this for early-out conditions that
   * the page wants to communicate to the client. */
  export class HttpError extends Error {
    readonly status: number;
    readonly headers: Headers;
    constructor(status: number, message?: string, init?: ResponseInit);
  }

  // -------------------------------------------------------------
  // Fragments (plan §14, FREEZE item 7, Amendment 4)
  // -------------------------------------------------------------

  /**
   * Mark a handler as a fragment (a named page subtree
   * reachable via an internal URL). The v2.0.0 shape is
   * `fragment(handler)` with default method `GET` -- the
   * `{ method, handler }` form is deferred to a follow-up
   * slice because it needs a real host-side fragment-method
   * validation step.
   *
   * Example:
   *
   * ```ts
   * import { fragment } from "tsp:server";
   *
   * export const userList = fragment(async (ctx) => {
   *   return ctx.services.users.list();
   * });
   * ```
   *
   * The fragment URL is built by the page via
   * `ctx.fragment("userList")` and is opaque to the
   * application.
   */
  export function fragment<Ctx extends Context = Context, T = unknown>(
    handler: (ctx: Ctx) => T | Promise<T>
  ): (ctx: Ctx) => T | Promise<T>;

  // -------------------------------------------------------------
  // HTML escape (plan §11)
  // -------------------------------------------------------------

  /** A `__tspRaw` value the renderer emits verbatim (slice 6
   * + slice 11). Use this to mark a string as pre-escaped HTML
   * so the renderer does NOT escape it again. */
  export interface RawNode {
    readonly __tspRaw: string;
  }
  /** Wrap a value as a `RawNode`. The renderer will emit it
   * verbatim. The application is responsible for ensuring the
   * string is already safe HTML. */
  export function raw(value: unknown): RawNode;

  // -------------------------------------------------------------
  // ID generation (slice 17a)
  // -------------------------------------------------------------

  /** Generate a 21-character url-safe id (default). */
  export function nanoid(size?: number): string;
  /** Build a generator that uses a custom alphabet. */
  export function customAlphabet(
    alphabet: string,
    defaultSize: number
  ): () => string;
  /** Build a generator that uses a custom random source. */
  export function customRandom(
    random: (bytes: number) => Uint8Array,
    alphabet: string,
    defaultSize: number
  ): () => string;
  /** Build a generator that uses a custom random source and
   * the default url-safe alphabet. */
  export function random(
    random: (bytes: number) => Uint8Array,
    defaultSize: number
  ): string;

  // -------------------------------------------------------------
  // Validation library (slice 17b)
  // -------------------------------------------------------------

  /**
   * The embedded zod 4 namespace. Pages can do:
   *
   * ```ts
   * import { zod } from "tsp:server";
   * const User = zod.object({ name: zod.string(), age: zod.coerce.number() });
   * const result = User.parse(body);
   * ```
   *
   * The runtime embeds zod 4.4.3 (63 KB vendor). The type
   * re-export points at the npm `zod` package so VSCode's
   * intellisense resolves to the real declarations.
   */
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  export const zod: typeof import("zod");

  // -------------------------------------------------------------
  // Database factory (slice 17d)
  // -------------------------------------------------------------

  /**
   * bun:sql factory. Use as a tagged template:
   *
   * ```ts
   * import { sql } from "tsp:server";
   * const conn = await sql`mysql://user:pass@host/db`;
   * const rows = await conn`SELECT * FROM users`;
   * await conn.close();
   * ```
   *
   * bun:sql is bun's native connection pool (Rust). Each page
   * invocation gets its own connection; per-worker pool reuse
   * happens inside bun. Pages are responsible for `close()`-ing
   * the connection before the handler returns.
   *
   * The typing is loose (`any` for the query result shape)
   * because bun:sql's parameter type is untyped at the
   * application boundary; users that need stricter typing
   * can wrap with a helper.
   */
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  export const sql: any;

  // -------------------------------------------------------------
  // Bun builtin namespace (slice 18 + Amendment 2)
  // -------------------------------------------------------------

  /**
   * The slice 18 + Amendment 2 `util` namespace. Mirrors
   * `__tspUtilNs__ = Object.freeze({...})` in
   * `bun/src/runtime/tsp/jsx.rs`. Pages that genuinely need a
   * subprocess / raw socket / native call belong in the host
   * (v2 worker / native service layer), not in a request-scoped
   * page module -- the high-risk bun builtins (`Bun.serve`,
   * `Bun.spawn`, `Bun.FFI`, `Bun.S3Client`, `Bun.connect`,
   * `Bun.mmap`, `Bun.Cookie`) are intentionally NOT exposed.
   */
  export interface UtilNamespace {
    /** Generate a v7 UUID (sortable + unique). */
    randomUUIDv7(): string;
    /** xxhash; numeric. */
    hash(data: Uint8Array | string): number;
    /** bun's `CryptoHasher` constructor (sha256, sha512, ...). */
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    CryptoHasher: any;
    /** bun's `Glob` for filesystem globs. */
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    Glob: any;
    /** TOML parser. */
    TOML: { parse(input: string): unknown };
    /** YAML parser. */
    YAML: { parse(input: string): unknown };
    /** Markdown -> HTML renderer. */
    markdown: { html(input: string): string };
    /** HTML-escape a string. */
    escapeHTML(value: unknown): string;
    /** gzip-compress bytes / string. */
    gzipSync(data: Uint8Array | string): Uint8Array;
    /** gzip-decompress bytes. */
    gunzipSync(data: Uint8Array): Uint8Array;
    /** bun's `Bun.file(path)` for a file reference. */
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    file: (path: string) => any;
    /** bun's `Bun.write(target, data)`. */
    write: (target: unknown, data: unknown) => Promise<number>;
    /** bun's `Bun.which(cmd)`; resolves a command on PATH. */
    which(command: string): string | null;
    /** bun's `Bun.peek(promise)`. */
    peek: <T>(p: Promise<T>) => Promise<T>;
    /** bun's `Bun.deepEquals(a, b)`. */
    deepEquals(a: unknown, b: unknown): boolean;
    /** bun's `Bun.deepMatch(pattern, value)`. */
    deepMatch(pattern: unknown, value: unknown): boolean;
    /** bun's `Bun.nanoseconds()`. */
    nanoseconds(): number;
    /**
     * Wrapped `Bun.env` -- `get(key)` and `has(key)` only.
     * The page CANNOT call `toJSON()` to dump every env var
     * (that would leak DB_PW / API_KEY / etc. that plan §17.1
     * says the host must not see). Use `get` / `has` to read
     * individual variables the operator told the page to use.
     */
    env: { get(key: string): string | undefined; has(key: string): boolean };
    /**
     * bun's native password hashing. Default is `argon2id`
     * (OWASP 2024+); `bcrypt` is exposed for legacy hash
     * interop (verifying existing user passwords stored as
     * `$2b$...`).
     */
    password: {
      hash(
        password: string,
        options?: { algorithm?: "bcrypt" | "argon2id" | "scrypt" }
      ): Promise<string>;
      verify(password: string, hash: string): Promise<boolean>;
      hashSync(
        password: string,
        options?: { algorithm?: "bcrypt" | "argon2id" | "scrypt" }
      ): string;
      verifySync(password: string, hash: string): boolean;
    };
  }
  export const util: UtilNamespace;
}
