// Generated by `tspserver_v2 typings`. Do not edit by hand.
//
// Plan §16.3 ("`tsp:runtime`") freezes three reads:
//
//   runtime.version       -- the tsp-v2 host version (string)
//   runtime.env           -- wrapped Bun.env (get/has only;
//                            no toJSON so the page cannot dump
//                            the whole process environment)
//   runtime.development   -- true when the host was started
//                            with TSP_DEVELOPMENT=1
//
// The page reaches them as:
//
// ```ts
// import { runtime } from "tsp:runtime";
// if (runtime.development) {
//   // dev-only behaviour
// }
// ```

declare module "tsp:runtime" {
  export interface Runtime {
    /** The host's version string (e.g. "0.4.0"). */
    readonly version: string;
    /**
     * Wrapped `Bun.env` -- `get(key)` and `has(key)` only.
     * The page CANNOT call `toJSON()` to dump every env var
     * (that would leak DB_PW / API_KEY / etc. that plan §17.1
     * says the host must not see). Use `get` / `has` to read
     * individual variables the operator told the page to use.
     */
    readonly env: { get(key: string): string | undefined; has(key: string): boolean };
    /** True when the host was started with `TSP_DEVELOPMENT=1`. */
    readonly development: boolean;
  }
  export const runtime: Runtime;
}
