# Global parameters
[global]
	ldap server require strong auth = No
	bind interfaces only = No
	dns forwarder = 8.8.8.8
	interfaces = lo eth0@if427
	netbios name = SAMBA-AD
	realm = EXAMPLE.COM
	server role = active directory domain controller
	workgroup = EXAMPLE
	idmap_ldb:use rfc2307 = yes

[sysvol]
	path = /usr/local/samba/var/locks/sysvol
	read only = No

[netlogon]
	path = /usr/local/samba/var/locks/sysvol/example.com/scripts
	read only = No
