[workspace]
resolver = "2"
members = [
  "crates/tsp-core",
  "crates/tsp-cli",
  "crates/tsp-jsc",
  "crates/tsp-js",
  "crates/tsp-http",
  "crates/tsp-runtime",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"

[profile.release]
lto = "thin"
codegen-units = 1
panic = "abort"
